@extends('layouts.app')
@section('title', 'report')
@push('css')
    <style>
        .container{
            text-align: center;
            border:2px solid;
            font-family: normal;
        }
        .example-table tr:nth-child(2n+1) {
            background-color: #ddd;
        }

        .example-table tr:nth-child(2n+0) {
            background-color: #eee;
        }

        .header-logo img {
            width: 40%;
        }

        .header tr {
            background: black !important;
            color: white;
            border: 1px solid black !important;

        }
        .header th {
            border-bottom: 2px solid #000000 !important;
        }

        td {
            border: 1px solid black !important;
        }
        .autority-section hr {
            margin-top: 20px;
            margin-bottom: 10px;
            border: 0;
            border-top: 2px solid #1d1c1c;
            width: 50%;
        }

        .confirm-section p {
            font-size: 16px;
        }

        .confirm-section {
            margin-top: 7%;
            margin-bottom: 5%;
            text-align: center;
        }

        .confirm-section hr {
            margin-top: 20px;
            margin-bottom: 5px;
            border: 0;
            border-top: 2px solid #000;
        }
      .header-title hr{
            margin-top: 20px;
            margin-bottom: 5px;
            border: 0;
            border-top: 2px solid #000;
          margin-top: 20px;
          margin-bottom: 10px;
          border: 0;
          border-top: 3px solid #1d1c1c;
          width: 31%;
      }
      .delivery .header-title hr{
          margin-top: 20px;
          margin-bottom: 5px;
          border: 0;
          border-top: 2px solid #000;
          margin-top: 10px;
          margin-bottom: 10px;
          border-top: 3px solid #1d1c1c;
          width: 16%;
      }
      .product-section{
          margin-top: 5%;
      }
        .generator-section, .product-table{
            margin-top: 3%;
        }
        .signature-generator hr {
            margin-top: 20px;
            margin-bottom: 5px;
            border: 0;
            border-top: 2px solid #000;
        }
        .purchase hr {
            margin-top: 9px;
            margin-bottom: 17px;
            border: 0;
            width: 100%;
            border-top: 3px solid #000;
        }
        .transfer hr {
            margin-top: 9px;
            margin-bottom: 17px;
            border: 0;
            width: 100%;
            border-top: 3px solid #000;
        }

        .second-section h3 strong {
            text-decoration: underline;
        }

        footer {
            margin-top: 5%;
        }


        .table-striped>tbody>tr:nth-of-type(odd) {
            background-color: #f9f9f9;
            color: black !important;
        }

        .tbody td {
            color: black;
        }

        .card-sale .card-header,
        .card-footer {
            background: #1cb24d;
        }

        .list-group-item p {
            font-family: 'Source Sans Pro', sans-serif;
        }
        .row{
            display: flex;
        }
        .col-md-3 {
            width: 25%;
        }
        .col-md-8 {
            width: 66.66666667%;
        }
        .col-md-2 {
            width: 16.66666667%;
        }
      .col-md-4 , .col-md-6{
          width: 50%;
      }
      .product-name{
          background: #E9E9E9;
          padding: 2px;
      }
   .purchase{
       text-align: left;

   }
   .transfer{
       text-align: right;
   }
   .delivery{
       margin: 3%;
   }


    </style>


@endpush
@section('content')

    <div class="content-wrapper">
        <section class="content">
            <div class="dashboard">
                <div class="container" id="report-print">
                    <div class="">
                        <div class="header-title text-center">
                             <h2> <strong>Product Report </strong> </h2>
                            <hr>
                             <span>02-08-2022 to 05-08-2022 </span>
                        </div>
                        <div class="product-section">
                            <h3> <strong>Ball P. Mehjabin -52"-Water</strong> </h3>
                            <span>Supplier : R-Craft Adding Date : XX July 2022 (User Name)</span>
                        </div>
                        <div class="generator-section">
                            This report is generated by user Name & Showing Deliverd Piceces
                                Report Mode is <strong> Total Pieces</strong>
                        </div>
                        <div class="product-table row">
                            <div class="col-md-3"></div>
                            <div class="col-md-6">
                                <table class="table table-bordered">

                                    <tbody>
                                    <tr>
                                        <td class="product-name" style="width: 50%">
                                          Product Name
                                        </td>
                                        <td style="width: 50%"><strong>Ball P. Mehjabin -52"-Water</strong></td>
                                    </tr>
                                    <tr>
                                        <td class="product-name" style="width: 50%">
                                            Suppliers
                                        </td>
                                        <td style="width: 50%"><strong>Ball P. Mehjabin -52"-Water</strong></td>
                                    </tr>
                                    <tr>
                                        <td class="product-name" style="width: 50%">
                                            SKU
                                        </td>
                                        <td style="width: 50%"><strong>Ball P. Mehjabin -52"-Water</strong></td>
                                    </tr>
                                    <tr>
                                        <td class="product-name" style="width: 50%">
                                            Barcode
                                        </td>
                                        <td style="width: 50%"><strong>Ball P. Mehjabin -52"-Water</strong></td>
                                    </tr>
                                    </tbody>
                                </table>

                            </div>
                            <div class="col-md-3"></div>
                        </div>

                        <div class="purchase-history row" >
                            <div class="col-md-2"></div>
                            <div class="col-md-8">
                            <div class="row">
                                <div class="col-md-6 purchase">
                                    <h4> <strong> Purchase History </strong> </h4>
                                    <hr>
                                    <div>01. 25 July 2022 (Purchase RCPT number)</div>
                                    <div>01. 25 July 2022 (Purchase RCPT number)</div>
                                    <div>01. 25 July 2022 (Purchase RCPT number)</div>
                                    <div>01. 25 July 2022 (Purchase RCPT number)</div>
                                    <div>01. 25 July 2022 (Purchase RCPT number)</div>
                                    <div>01. 25 July 2022 (Purchase RCPT number)</div>
                                    <div class="strong"> <strong>Total Bought 04 times </strong> </div>
                                </div>
                                <div class="col-md-6 transfer">
                                    <h4> <strong> Transfer History </strong> </h4>
                                    <hr>
                                    <div>01. 25 July 2022 (Purchase RCPT number)</div>
                                    <div>01. 25 July 2022 (Purchase RCPT number)</div>
                                    <div>01. 25 July 2022 (Purchase RCPT number)</div>
                                    <div>01. 25 July 2022 (Purchase RCPT number)</div>
                                    <div>01. 25 July 2022 (Purchase RCPT number)</div>
                                    <div>01. 25 July 2022 (Purchase RCPT number)</div>
                                    <div class="strong"> <strong>Total Bought 04 times </strong> </div>
                                </div>
                            </div>
                        </div>
                            <div class="col-md-2"></div>

                        </div>
                        <div class="delivery_pce">
                            <h4> <strong style="border: 3px solid black;padding: 8px;"> DELIVERD : 254 PCS </strong> </h4>
                           <div style="margin-top: 3%">
                               <strong>in words</strong>
                           </div>
                            <p>Total deliverd tow hundred fifty four pieces </p>
                        </div>
                        <div class="delivery">
                            <div class="header-title text-center">
                                <h4> <strong>DELIVERD PIECES </strong> </h4>
                                <hr>

                            </div>
                            <div class="branch-pec">
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Main Branch - 00 pcs</strong>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Online Branch - 00 pcs</strong>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Online Branch - 00 pcs</strong>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Online Branch - 00 pcs</strong>
                                    </div>
                                </div>
                            </div>
                            <div class="delivery-table">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr style="font-weight: bold">
                                        <td >SL</td>
                                        <td >First</td>
                                        <td >Last</td>
                                        <td >Handle</td>
                                        <td >Handle</td>
                                        <td>Handle</td>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td >1</td>
                                        <td>Mark</td>
                                        <td>Otto</td>
                                        <td>@mdo</td>
                                        <td>@mdo</td>
                                        <td>@mdo</td>
                                    </tr>
                                    <tr>
                                        <td >2</td>
                                        <td>Jacob</td>
                                        <td>Thornton</td>
                                        <td>Thornton</td>
                                        <td>Thornton</td>
                                        <td>@fat</td>
                                    </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="delivery" style="margin-top: 5%;">
                            <div class="header-title text-center">
                                <h4> <strong>AVILABLE PIECES </strong> </h4>
                                <hr>

                            </div>
                            <div class="branch-pec">
                                <div class="row">
                                    <div class="col-md-3">
                                        <strong>Main Branch - 00 pcs</strong>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Online Branch - 00 pcs</strong>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Online Branch - 00 pcs</strong>
                                    </div>
                                    <div class="col-md-3">
                                        <strong>Online Branch - 00 pcs</strong>
                                    </div>
                                </div>
                            </div>
                            <div class="delivery-table">
                                <table class="table table-bordered">
                                    <thead>
                                    <tr style="font-weight: bold">
                                        <td >SL</td>
                                        <td >Branch</td>
                                        <td width="50%" >Transferred</td>
                                        <td>Avilable</td>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td >1</td>
                                        <td>@mdo</td>
                                        <td>@mdo</td>
                                        <td>@mdo</td>
                                    </tr>
                                    <tr>
                                        <td >2</td>
                                        <td>Thornton</td>
                                        <td>Thornton</td>
                                        <td>@fat</td>
                                    </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div>


                        <div class="">
                            <div class="confirm-section row">
                                <div class="col-md-2"></div>
                                <div class="col-md-8">
                                    <p>C O N F I R M E D</p>
                                    <hr>
                                </div>
                                <div class="col-md-2"></div>
                            </div>
                            <div class="autority-section row" style="display: flex;">
                                <div class="col-md-2"></div>
                                <div class="col-md-4" style="width: 50%;">
                                    <hr>
                                    <p>Authority</p>
                                </div>
                                <div class="col-md-4" style="width: 50%;">
                                    <hr>
                                    <p>Receiver</p>
                                </div>
                                <div class="col-md-2"></div>
                            </div>
                        </div>
                        <footer>
                            <div class="footer-section">
                                <p>House-36, Road-05, Block-B, Banasree, Rampura.</p>
                                <span>www.colourful.com.bd</span> <span>01785-992233</span>
                                <span>collourfuloffice@gmail.com</span>
                            </div>
                        </footer>
                    </div>
                </div>
            </div>
        </section>
        <div class="text-center" style="margin: 2%;">
            <button class="btn text-black print pointer hidden-print"
                    style=" margin-right:20px; color: black;border-color: #000000;background: white;">Print</button>
            <a href="" class="btn text-black print pointer hidden-print"
               style=" margin-right:20px; color: black;border-color: #000000;background: white;">Download</a>
        </div>
    </div>
@endsection
